use etlclass;
select * from health_care_sql;
alter table health_care_sql rename to healthcare;
select * from healthcare;

-- 1. Retrieve the names of all patients in the database. --
select name as patients_name from healthcare;

-- 2. List the unique medical conditions present in the dataset. --
select distinct(medical_condition) from healthcare;

-- 3. Find the total number of doctors in the healthcare system. --
select count(doctor) as total_no_of_doctor from healthcare;

-- 4. Retrieve the details of all female patients. --
select * from healthcare where gender ="female";

-- 5. what is the average age of patients in the database. --
select avg(age) as Avg_patient_age from healthcare;

-- 6. Identify the patients who have more than one medical condition. --
select name,count(distinct medical_condition) as no_condition from healthcare group by name having count(distinct Medical_condition ) > 1;

-- 7. List the names of all doctors. --
select Doctor as name_of_all_doctors from healthcare;

-- 8.Identify the most common medical condition among patients. --
select max(Medical_condition) as most_common_medical_condition_among_patients from healthcare;

-- 9.Find the patients who are older than 60 years and have diabetes. --
select name as "patients>60" from healthcare where age >= 60;

-- 10.Calculate the total revenue generated by the healthcare system. --
select sum(billing_amount) as total_revenue from healthcare;

-- 11.Find the doctor with the oldest patient. --
select Doctor,max(age) from healthcare group by doctor having max(age);

-- 12.Calculate the average duration of medical visits. --
select avg(duration) as medical_visit_duration from healthcare;

-- 13.Give the names of patients whose name starts with A. --
select name as patient_name from healthcare where name like "a%";

-- 14.How many male and female patients are there in dataset. --
select gender,count(name) from healthcare group by gender;

-- 15.how many patients are normal. --
select name from healthcare where test_results ="normal";

-- 16.how many patients are abnormal or Inconclusive. --
select count(name) from healthcare where test_results in ("abnormal","Inconclusive");

-- 17.how many patients of blood group AB+ are there of age above 52. --
select count(name) from healthcare where blood_type = "AB+" and age>=52;

-- 18. how many patients have paid the bill above 24890. --
select count(name) from healthcare where billing_amount >= 24890;

-- 19. what are the names of patients having Asthma. --
select count(name) from healthcare where medical_condition = "asthma";

-- 20. how many patients have cancer. --
select count(name) from healthcare where medical_condition = "CANCER";

-- 21. what are the names and blood groups of patients admitted to room no. 292. --
select name,blood_type from healthcare where room_number = 292;
-- 22. how many males have Arthritis. --
select count(gender),medical_condition from healthcare where gender = "male" and medical_condition ="Arthritis";

-- 23. How many patients were admitted to Harris and Sons hospital. --
select count(name),hospital from healthcare where hospital = "Harris and Sons";

-- 24. what are the names of patients whose Insurance Provider are Cigna. --
select name,insurance_provider from healthcare where insurance_provider = "Cigna";

-- 25. Name the Medical Condition having patients whose ages is greater than average age. --
select distinct medical_condition,name,age from healthcare where age > (select avg(age) from healthcare);