-- 1 what are the lengths of fnames of all employees. --
-- 2. add a column location. --
-- 3. what is the 3rd   highest salary. --
-- 4. add a constraint to id for filling values automatically. --
-- 5. what is the lname of employee having highest salary. --
-- 6. what are the names of employees having 'e' in their fname. --
-- 7. what are the salaries of empid 3 and empid 7. --
-- 8. change the gender of empid 4 to male. --
-- 9. show the 4th and 5th record of data. --
-- 10. show the name and age of employee having second highest salary. --
-- 11. change the salary of id 5 to 90000. --
-- 13. show the names of employees having id from 4 to 7. --
-- 15. add the record of a male named as divijay singh ,having salary 99000 joined on 02-02-1999. --
-- 16. show the repeated values in salary column. --
-- 17. create a view containing the info of id 5,6,4. --
-- 22. add values to location column , if id is less than 4 then 'airoli' else 'ghansoli'. --
-- 23. replace the 'a' in fnames by '@' of employees. --
-- 24. extract initials(1st letter) of lnames of employees . --
-- 25. add a column state , and fill the values as if the length of fname is greater than 4 then 'sikkim' if it is less than 4 than 'kerala'. --
-- 26. add joining date of 8 employees as id=1 > 11/jan/2011  2 > 12/jan/2011......8 > 18/jan/2011 --
-- 28. what is the experience of all employees till 10/feb/2019 in days. --
-- 29. show the weekday number of all employees of joining date. --
-- 30. show the weekday name of joining date of all employees. --
-- 31. show the highest salary in females. --
-- 32. show the 2nd highest salary in males --